services:
  celery:
    environment:
      - MODO_PRUEBA_VIDEO=1
      - IS_DOCKER=1
      - STORAGE_ROOT=/storage

  celery_worker:
    environment:
      - MODO_PRUEBA_VIDEO=1
      - IS_DOCKER=1
      - STORAGE_ROOT=/storage

  celery_video2:
    environment:
      - MODO_PRUEBA_VIDEO=1
      - IS_DOCKER=1
      - STORAGE_ROOT=/storage

  celery_manifest:
    environment:
      - MODO_PRUEBA_VIDEO=1
      - IS_DOCKER=1
      - STORAGE_ROOT=/storage

  fastapi:
    environment:
      - STORAGE_ROOT=/storage
